### ISSUE TITLE
Example websocket for javascript or C#

### ISSUE THREAD

**Issue by tomeroto** [bitcoinaverage/api-integration-examples#14]
Hi There,

I just open an example for JS and C#. And I there is no an example line of code how to use the classes or object for socket.

Im not expert on JS or C#, but can you give me complete example how to call the object or class?

Thank you

**Comment by goraniliev** [comment]
@tomeroto did you check the examples [here](https://github.com/bitcoinaverage/api-integration-examples/tree/master/node_npm_examples/websocket) which use the [bitcoinaverage NPM library](https://www.npmjs.com/package/bitcoinaverage)? That should be the easiest way to connect to the websockets with Javascript.

**Comment by tomeroto** [comment]
hi @goraniliev thank you for your response, the javasript example is good for me, by the way there is example for C#?

**Comment by goraniliev** [comment]
@tomeroto Maybe this [C# wrapper](https://github.com/bitcoinaverage/api-integration-examples/blob/master/csharp-examples/csharp-wrapper.cs) can help you. If not, you can try to write your implementation and if you think it could be useful for other users, feel free to make a PR ;)
